#!/usr/bin/python
from mdv.sec.sekt import SektCommand

import os

class Cve(SektCommand):

    descr = "show information about a given CVE"

    def init_parser(self, parser):
        super(Cve, self).init_parser(parser)
        parser.add_option("-s", "--strict", action="store_true",
                default=False, help="search using exact match")

    def run(self):
        #TODO iterate over self.args
        if not self.args:
            return
        cveid = self.args[0]
        try:
            found = self.tasks.find_cve(cveid,
                    strict=self.opts.strict, dump=True)
            for cveid, rawcve in found:
                print rawcve
        except IOError, e:
            if e.errno != 32: # broken pipe
                raise

Cve().main()

# vim:ts=4:sw=4:et
