#!/usr/bin/python
from mdv.sec.sekt import SektCommand

class Pkg(SektCommand):

    descr = "Dumps configuration values"

    def run(self):
        print repr(self.config)

Pkg().main()

# vim:ts=4:sw=4:et
