#!/usr/bin/python
import sys
import os

def parse_options(args):
    import optparse
    def parse_option(option, opt_str, value, parser, *args, **kwargs):
        kv = value.split("=", 1)
        if len(kv) != 2:
           raise optparse.OptionValueError, "-o accepts values only in "\
                   "the name=value form"
        levels = kv[0].split(".")
        lastv = kv[1]
        for name in levels[:0:-1]:
            lastv = {name: lastv}
        parser.values.config_options[levels[0]] = lastv
    parser = optparse.OptionParser("%prog [options]")
    parser.set_defaults(config_options={})
    parser.add_option("--init", action="store_true", default=False,
            help="create initial directory structure needed for sekt")
    parser.add_option("--pull-cves", action="store_true", default=False,
            help="pull cves from a MITRE's XML text file")
    parser.add_option("--pull-medias", action="store_true", default=False,
            help="Pull packages from medias")
    parser.add_option("--fetch-kernel-changelogs", action="store_true",
            default=False, help="Download new kernel changelogs")
    parser.add_option("--parse-kernel-changelogs", action="store_true",
            default=False, help="Load kernel changelogs into database")
    parser.add_option("--cve", type="string", default=None,
            help="show information about a given CVE")
    parser.add_option("--pkg", type="string", default=None,
            help="find a package (as in urpmq -y)")
    parser.add_option("--cve-keywords", type="string", default=None,
            help="show matching keywords for CVEs")
    parser.add_option("--kci", type="string", default=None,
            help="find kernel releases with a given commit message")
    parser.add_option("-e", "--easy-tickets", action="store_true",
            default=False, help="show easy to fix tickets")
    parser.add_option("-s", "--status", action="store_true", default=False,
            help="show the status of the tickets for each distro")
    parser.add_option("--showrc", action="store_true", default=False,
            help="dump sekt configuration")
    parser.add_option("-v", "--verbose", action="store_true", default=False)
    parser.add_option("-o", "--option", type="string", action="callback",
            callback=parse_option,
            help="set one configuration option in the form opt=val")
    parsed = parser.parse_args(args)
    return parsed

def run(options, args):
    from mdv.sec.tasks import Interface, Config, SecteamTasks, Error
    config = Config()
    config.merge(options.config_options)
    path = (os.environ.get(config.conf.path_environment) or
            os.path.expanduser(os.path.join("~", config.conf.user_file)))
    if os.path.exists(path):
        config.load(path)
    tasks = SecteamTasks(config)
    interface = Interface(config, tasks)
    try:
        try:
            if options.init:
                interface.init()
            if options.pull_cves:
                interface.pull_cves()
            if options.pull_medias:
                interface.pull_packages()
            if options.fetch_kernel_changelogs:
                interface.fetch_kernel_changelogs()
            if options.parse_kernel_changelogs:
                interface.parse_kernel_changelogs()
            if options.cve:
                interface.dump_cve(options)
            if options.pkg:
                interface.find_packages(options)
            if options.cve_keywords:
                interface.correlate_cves_packages(options)
            if options.kci:
                interface.find_kernel_commit(options)
            if options.easy_tickets:
                interface.easy_tickets()
            if options.status:
                interface.status()
            if options.showrc:
                interface.dump_conf()
        finally:
            tasks.finish()
    except Error, e:
        sys.stderr.write("error: %s\n" % e)
        sys.exit(1)
    except KeyboardInterrupt:
        sys.stderr.write("interrupted\n")
        sys.exit(1)

def setup_logging(options):
    import logging
    if options.verbose:
        logging.basicConfig(level=logging.DEBUG)
    else:
        logging.basicConfig(level=logging.ERROR)

def main():
    options, args = parse_options(sys.argv)
    setup_logging(options)
    run(options, args)

if __name__ == "__main__":
    main()
