#!/usr/bin/python
from mdv.sec.sekt import SektCommand

class Pkg(SektCommand):

    descr = "Dumps configuration values"

    def run(self, config, tasks):
        print repr(config)

Pkg().main()

# vim:ts=4:sw=4:et
